version: "3"
services:
  node_react_builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    ports:
      - 999:3000
    restart: unless-stopped
    volumes:
      - build:/home/node:z
    container_name: $BUILDER

volumes:
  build:
    driver_opts:
      o: bind
      type: none
      device: ./build
